### PR TITLE
Better readability

### PR DESCRIPTION
**Pull request by NickSdot**
Thanks for your hard work! You've asked for feedback on Twitter, so here we go.

In my opionion this way is much more structured and readable in both, code and frontend. Just edited the first table.

### CODE REVIEW

**Comment by PovilasKorop** [comment]
@NickSdot hi Nick, thanks for the effort for the change.

I thought about that layout as well and tried it out locally, it has a better separation of sections, but has its own drawbacks:

- Different lengths of tables so it's even worse for eyes to read, jumping left/right
- The section titles can't have their own links, to full courses, for example - I have a few cases when I need it

So not sure, for now I think I will stick to my own layout. But thanks for the effort, I do appreciate it!

**Comment by NickSdot** [comment]
@PovilasKorop you are rigtht, the table sizes were indeed better before. 

Comitted another idea, maybe you like this better. The most import is imho to get the types out of the titles and each entry in a own row. But in the end up to you! :-)

**Comment by PovilasKorop** [comment]
@NickSdot mm, not sure. Maybe it looks better on your screen (not sure about the size), but here's how it looks on mine: 
Screenshot 2021-07-23 at 16 33 52

1. The longest link title then defines the length of the second column
2. Then the third column is visually totally separated so people need to jump left-right to see what link type is.
3. And also third column then has "Official docs" on two lines, and then each row becomes higher and whole readme is longer then. With general rows are even higher than the title rows.

**Comment by NickSdot** [comment]
@PovilasKorop yep, looks the same here. 

From an user perspective I myself rather would like to have more space and structure instead of elements sticking to each other without space. Neither like to always first need to read the type until I know the real link title.

But that's pretty much a matter of taste of course!

Feel free to close the PR. It was just an idea and I am ok with it not getting accepted. 👌😎

Or get more feedback from your audience. Two screenshots next to each other with a poll on Twitter maybe. Cheers.

**Comment by PovilasKorop** [comment]
@NickSdot let people decide :) https://twitter.com/PovilasKorop/status/1418574857835589640

**Comment by NickSdot** [comment]
@PovilasKorop 🚀💪😬

**Comment by JustinByrne** [comment]
What about creating a GitHub pages website to show this. You could then make a mobile and desktop version, happy to mock up some idea if you want.

**Comment by PovilasKorop** [comment]
@JustinByrne thanks for the offer, but, to be honest, I don't think it's worth the effort. As poll on Twitter shows, people are fine with current layout.

**Comment by JustinByrne** [comment]
Alternate solution then to shorten the width of the page. What about using emjois to signify what the link is. So for example you could use 📖 for official docs and a 🎬 for the videos.

Only suggesting as the page is quite squished for a mobile.

**Comment by PovilasKorop** [comment]
@JustinByrne what an awesome idea! Yes, that shortens the content without losing its meaning. Thanks, merged the PR and will make some small tweaks, like add emoji for courses.

@NickSdot will close your PR, sorry, the new layout wasn't an overwhelming winner in this poll :) 

Screenshot 2021-07-24 at 08 14 51

But, with Justin's changes, I think your suggestion is resurrected from another angle and looks more readable already.

**Pull request closed without merging**
